const NAME_SPACE = 'Companies';

const constants = {
  FETCH_COMPANIES_CANCEL: `${NAME_SPACE}/FETCH_COMPANIES_CANCEL`,
  FETCH_COMPANIES_FAILURE: `${NAME_SPACE}/FETCH_COMPANIES_FAILURE`,
  FETCH_COMPANIES_REQUEST: `${NAME_SPACE}/FETCH_COMPANIES_REQUEST`,
  FETCH_COMPANIES_SUCCESS: `${NAME_SPACE}/FETCH_COMPANIES_SUCCESS`,
  FETCH_COMPANIES: `${NAME_SPACE}/FETCH_COMPANIES`
};

export default constants;